### ISSUE TITLE
Unexpected Token in generics

### ISSUE THREAD

**Issue by AnsonT** [davidje13/neutrino-typescript-eslint#2] opened 2021-03-02 18:27 UTC
```
class Foo2<F extends Foo> {
}
```

Unexpected token on 'extends'

**Comment by davidje13** [comment] 2021-03-02 19:12
Please provide your `.neutrinorc.js` file. I can't do much to debug if I don't know which linting rules you are translating.

**Comment by davidje13** [comment] 2021-03-20 12:30
I am unable to reproduce this issue with the following code:

```ts
class Foo {}
class SubFoo extends Foo {}
class Foo2<F extends Foo> {}

console.log(new Foo2<SubFoo>());

export {} // mark file as module
```

With the following neutrinorc file:

```js
const typescript = require('neutrinojs-typescript');
const typescriptLint = require('neutrinojs-typescript-eslint');
const node = require('@neutrinojs/node');
const jest = require('@neutrinojs/jest');
const eslint = require('@neutrinojs/eslint');

module.exports = {
  use: [
    typescript(),
    typescriptLint(),
    eslint(),
    jest(),
    node(),
  ],
};
```

And the following dependencies:

```
├── @neutrinojs/eslint@9.5.0
├── @neutrinojs/jest@9.5.0
├── @neutrinojs/node@9.5.0
├── @types/jest@26.0.21
├── eslint@7.22.0
├── jest@26.6.3
├── neutrino@9.5.0
├── neutrinojs-typescript-eslint@1.3.1
├── neutrinojs-typescript@1.1.6
├── typescript@4.2.3
├── webpack-cli@3.3.12
└── webpack@4.46.0
```

(I also tried TypeScript 4.1.x and 4.0.x)

I get a correct warning that `F` is never used, but it parses the syntax just fine.

Are you sure you aren't using generics in a `.js` file? TypeScript only supports generics (and types) in `.ts` files, not `.js`.

---

I'm going to close this for now because I can't reproduce the issue. But if you provide more details about your setup (e.g. a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)) I'm happy to reopen it and investigate further.

**Closed as completed by davidje13** 2021-03-20 12:30 UTC
Labels: cannot reproduce
